name: API Build & Deployment

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.SA_EMAIL }}'

    - name: Create IMAGE_NAME environment variable
      run: echo "IMAGE_NAME=${{ secrets.GCP_REGION_PROJECT_REPO }}/image:$(date +%s)" >> $GITHUB_ENV

    - name: Download model into local directory
      run: |
        mkdir model
        gcloud storage cp gs://${{ secrets.GCS_MODEL_PATH }}/* ./model/

    - name: Build the Docker image
      run: |
        gcloud auth configure-docker australia-southeast2-docker.pkg.dev
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }} --build-arg model_path=${{ vars.MODEL_PATH }}

    - name: Push Image to GCP Artifact Registry
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy image to cloud run
      run: gcloud run deploy ${{ vars.SERVICE_NAME }} \
      --image=${{ env.IMAGE_NAME }} \
      --cpu=1 \
      --max-instances=2 \
      --memory=4Gi \
      --port=8080 \
      --region=${{ vars.GCP_REGION }} \
      --cpu-boost
      