name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.SA_EMAIL }}'

    - name: Create IMAGE_NAME environment variable
      run: echo "IMAGE_NAME=${{ secrets.GCP_REGION_PROJECT_REPO }}/image:$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        gcloud auth configure-docker australia-southeast2-docker.pkg.dev
        docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Push Image to GCP Artifact Registry
      run: docker push $IMAGE_NAME

    - name: Deploy image to cloud run
      run: gcloud run deploy ${{ vars.SERVICE_NAME }} --image $IMAGE_NAME
