name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  commit:
    branches: [ "22-feat-fix-ci-deployment" ]

env:
  TIMESTAMP: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.SA_EMAIL }}'

    - name: Build the Docker image
      run: |
        gcloud auth configure-docker australia-southeast2-docker.pkg.dev
        docker build . --file Dockerfile --tag ${{ secrets.GCP_REGION_PROJECT_REPO }}/image:latest

    - name: Push Image to GCP Artifact Registry
      run: docker push ${{ secrets.GCP_REGION_PROJECT_REPO }}/image:latest
